CREATE DATABASE [NHibernateSimple]
GO
USE [NHibernateSimple]
GO

DROP TABLE Teacher
DROP TABLE Class
DROP TABLE Family
DROP TABLE Student

CREATE TABLE Teacher(
	Id VARCHAR(64) NOT NULL,
	Name NVARCHAR(32) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE Class(
	Id VARCHAR(64) NOT NULL,
	Name NVARCHAR(20) NOT NULL,
	TeacherId VARCHAR(64) NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (TeacherId) REFERENCES Teacher(Id)
);


CREATE TABLE Student(
	Id VARCHAR(64) NOT NULL,
	Name NVARCHAR(20) NOT NULL,
	ClassId VARCHAR(64) NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (ClassId) REFERENCES Class(Id)
);

CREATE TABLE Family(
	Id VARCHAR(64) NOT NULL,
	Address NVARCHAR(64) NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (Id) REFERENCES Student(Id)
)

CREATE TABLE Customer(
	Id VARCHAR(64) NOT NULL,
	Name NVARCHAR(32) NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE [Role](
	Id VARCHAR(64) NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE CustomerRole(
	CustomerId VARCHAR(64) NOT NULL,
	RoleId VARCHAR(64) NOT NULL,
	IsActive BIT NOT NULL DEFAULT(0),
	FOREIGN KEY (CustomerId) REFERENCES Customer(Id),
	FOREIGN KEY (RoleId) REFERENCES Role(Id)
)

CREATE TABLE Product(
	Id VARCHAR(64) NOT NULL,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	MiddleName NVARCHAR(20),
	PRIMARY KEY (Id)
)

DROP TABLE [CustomerRole]
DROP TABLE [Customer]
DROP TABLE [Role]

DELETE FROM Family
DELETE FROM Student
DELETE FROM Class
DELETE FROM Teacher

DELETE FROM [Customer]
DELETE FROM [CustomerRole]
DELETE FROM [Role]

SELECT * FROM [Customer]
SELECT * FROM [CustomerRole]
SELECT * FROM [Role]

