CREATE DATABASE [NHibernateSimple]
GO
USE [NHibernateSimple]
GO

DROP TABLE [OrderProduct]
DROP TABLE [Order]
DROP TABLE [Product]
DROP TABLE [Customer]
CREATE TABLE Customer(
	Id VARCHAR(64) NOT NULL,
	FirstName NVARCHAR(32),
	LastName NVARCHAR(32),
	Version VARCHAR(32),
	PRIMARY KEY (Id)
)

CREATE TABLE Product(
	Id VARCHAR(64) NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Version VARCHAR(32),
	Price DECIMAL NOT NULL DEFAULT(0.00),
	PRIMARY KEY (Id)
)

CREATE TABLE [Order](
	Id VARCHAR(64) NOT NULL,
	UtcCreatedOn DATETIME,
	CustomerId VARCHAR(64) NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (CustomerId) REFERENCES Customer(Id)
)

CREATE TABLE [OrderProduct]
(
	OrderId VARCHAR(64) NOT NULL,
	ProductId VARCHAR(64) NOT NULL,
	FOREIGN KEY (OrderId) REFERENCES [Order](Id),
	FOREIGN KEY (ProductId) REFERENCES [Product](Id)
)

